---
title: "COVID-19 in Spain"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
    orientation: rows
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(coronavirus)
library(DT)
library(plotly)
library(ztable)

nacional_covid19 <- read.csv("https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/nacional_covid19.csv") %>% 
  mutate(fecha = as.Date(fecha, format = "%Y-%m-%d")) %>% 
  mutate(activos = casos - altas - fallecimientos) %>% 
  mutate(rownum = row_number()) %>% 
  mutate(casos_anteriores = ifelse(rownum == 1, NA, dplyr::lag(casos))) %>% 
  mutate(variacion_casos = casos - casos_anteriores) %>% 
  mutate(variacion_uci = ifelse(rownum == 1, NA, 
                                     ingresos_uci - dplyr::lag(ingresos_uci))) %>% 
  mutate(variacion_activos = ifelse(rownum == 1, NA, 
                                     activos - dplyr::lag(activos))) %>% 
  mutate(variacion_altas = ifelse(rownum == 1, NA, 
                                     altas - dplyr::lag(altas))) %>% 
  mutate(variacion_fallecimientos = ifelse(rownum == 1, NA, 
                                     fallecimientos - dplyr::lag(fallecimientos))) %>% 
  select(fecha, casos, variacion_casos, ingresos_uci, variacion_uci, altas,
         variacion_altas, fallecimientos, variacion_fallecimientos, activos,
         variacion_activos) %>% 
  dplyr::arrange(desc(fecha))
  

ccaa_covid19_altas <- read.csv("https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_altas.csv")
ccaa_covid19_casos <- read.csv("https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_casos.csv")
ccaa_covid19_fallecidos <- read.csv("https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_fallecidos.csv")
ccaa_covid19_uci <- read.csv("https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_uci.csv") 

data("coronavirus")
coronavirus_es <- coronavirus %>% 
  filter(Country.Region == "Spain")

coronavirus_es

vline <- function(x = 0, color = "grey") {
  list(
    type = "line", 
    y0 = 0, 
    y1 = 1, 
    yref = "paper",
    x0 = x, 
    x1 = x, 
    line = list(color = color, dash = 'dot')
  )
}

vannotation <- function(mytext,  xcoord, ycoord = 0) {
  list(yref = 'paper', 
       xref = "x", y = ycoord, x = xcoord, text = mytext)
}

# caption <- function(mytext) {
#   list(x = 1, y = -0.1, text = mytext, 
#       showarrow = F, 
#       xref = 'paper', yref = 'paper', 
#       xanchor = 'right', yanchor = 'top', xshift = 0, yshift = 0,
#       font = list(size = 10, color = "grey")
#       )
# }

caption <- function(mytext) {
  list(text = mytext, 
       x = 1,
       y = -0.05,
       showarrow = F, 
       xref = 'paper', yref = 'paper', 
       xanchor = "right",
       yanchor = "bottom",
       # xanchor = 'right', yanchor = 'top', xshift = 0, yshift = 0,
       font = list(size = 10, color = "grey")
       )
}


```

Gráficos España
=====================================  

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Variación

```{r}
plot_ly(data = nacional_covid19) %>% 
  add_trace(x = ~ fecha,
            y = ~ variacion_casos,
            type = "scatter",
            mode = "lines+markers",
            name = "Variación de casos") %>% 
    add_trace(x = ~ fecha,
            y = ~ variacion_activos,
            type = "scatter",
            mode = "lines+markers",
            name = "Variación de casos activos") %>% 
    add_trace(x = ~ fecha,
            y = ~ variacion_altas,
            type = "scatter",
            mode = "lines+markers",
            name = "Variación de casos recuperados") %>% 
  add_trace(x = ~ fecha,
            y = ~ variacion_fallecimientos,
            type = "scatter",
            mode = "lines+markers",
            name = "Variación de fallecimientos") %>% 
  layout(shapes = list(vline("2020-03-13", "grey"), vline("2020-03-16", "grey")),
         annotations = list(
           caption("Datos: Ministerio de Sanidad a través de Datadista"),
           vannotation("Confinamiento voluntario", "2020-3-13", 0.5),
           vannotation("Confinamiento obligatorio", "2020-3-16", 0.75)),
         title = "Evolución de variacion de casos del COVID-19 con respecto al día anterior, en España",
         yaxis = list(title = "Número de casos"),
         xaxis = list(title = "Fecha"),
         legend = list(x = 0.1, y = 0.9),
         hovermode = "compare")  


```

### Acumulados

```{r}

plot_ly(data = nacional_covid19) %>% 
  add_trace(x = ~ fecha,
            y = ~ casos,
            type = "scatter",
            mode = "lines+markers",
            name = "Casos detectados") %>% 
  add_trace(x = ~ fecha,
            y = ~ activos,
            type = "scatter",
            mode = "lines+markers",
            name = "Casos activos") %>% 
   add_trace(x = ~ fecha,
            y = ~ altas,
            type = "scatter",
            mode = "lines+markers",
            name = "Casos recuperados") %>% 
  add_trace(x = ~ fecha,
            y = ~ fallecimientos,
            type = "scatter",
            mode = "lines+markers",
            name = "Fallecimientos por COVID19") %>% 
  layout(shapes = list(vline("2020-03-13", "grey"), vline("2020-03-16", "grey")),
         annotations = list(
           vannotation("Confinamiento voluntario", "2020-3-13", 0.5),
           vannotation("Confinamiento obligatorio", "2020-3-16", 0.75),
           caption("Datos: Ministerio de Sanidad a través de Datadista")),
         title = "Evolución del COVID-19 en España",
         yaxis = list(title = "Número de casos"),
         xaxis = list(title = "Fecha"),
         legend = list(x = 0.1, y = 0.9),
         hovermode = "compare")  
  
```

### Variación Columnas
```{r}
plot_ly(data = nacional_covid19) %>% 
  add_trace(x = ~ fecha,
            y = ~ variacion_casos,
            type = "bar",
            # mode = "lines+markers",
            name = "Variación de casos") %>% 
  layout(shapes = list(vline("2020-03-13", "grey"), vline("2020-03-16", "grey")),
         annotations = list(
           vannotation("Confinamiento voluntario", "2020-3-13", 0.5),
           vannotation("Confinamiento obligatorio", "2020-3-16", 0.75),
           caption("Datos: Ministerio de Sanidad a través de Datadista")),
         title = "Evolución de variacion de casos del COVID-19 en España",
         yaxis = list(title = "Número de casos"),
         xaxis = list(title = "Fecha"),
         legend = list(x = 0.1, y = 0.9),
         hovermode = "compare")  
  
```

Datos
=====================================  

Row
-----------------------------------------------------------------------

### Tabla de datos

```{r}
datatable(nacional_covid19, 
          colnames = c('Fecha', 'Casos', 'Variación casos', 
                       'Ingresos UCI', 'Variación UCI', 
                       'Altas', 'Variación de altas',
                       'Fallecimientos', 'Variación de fallecimientos',
                       'Casos activos', 'Variación de activos'),
          options = list(
            # columnDefs = list(list(className = 'dt-center', targets = 5)),
            pageLength = 20, 
            lengthMenu = c(10, 20, 30))) %>% 
  formatRound(columns = 2:11, digits = 0, mark = ".", dec.mark = "") %>% 
  formatStyle(
    'variacion_casos',
    background = styleColorBar(nacional_covid19$variacion_casos, 'steelblue'),
    backgroundSize = '100% 90%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center') %>% 
  formatStyle(
    'variacion_uci',
    background = styleColorBar(nacional_covid19$variacion_uci, 'pink'),
    backgroundSize = '100% 90%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center') %>% 
  formatStyle(
    'variacion_altas',
    background = styleColorBar(nacional_covid19$variacion_altas, '#2C9F2C'),
    backgroundSize = '100% 90%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center') %>% 
  formatStyle(
    'variacion_fallecimientos',
    background = styleColorBar(nacional_covid19$variacion_fallecimientos, '#D62728'),
    backgroundSize = '100% 90%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center') %>% 
  formatStyle(
    'variacion_activos',
    background = styleColorBar(nacional_covid19$variacion_activos, '#FF7F0E'),
    backgroundSize = '100% 90%',
    backgroundRepeat = 'no-repeat',
    backgroundPosition = 'center')

```
